[providers]
providers = ["node", "python"]

[phases.setup]
nixPkgs = ["nodejs-20_x", "python312Packages.pip", "gcc"]

[phases.install]
cmds = ["npm ci", "pip install -r api/requirements.txt"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
