apiVersion: v1
kind: ConfigMap
metadata:
  name: sentibot-config
  namespace: default
data:
  NODE_ENV: "production"
  PYTHONUNBUFFERED: "1"
  PORT: "3000"
  FASTAPI_PORT: "8000"
  TEAM_NAME: "AI Experts"
  TEAM_LEADER: "Aryan Sharma"
